name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI-SKIP]')"
    steps:
      - uses: actions/checkout@v3
      - name: Lint Check
        uses: musichin/ktlint-check@v2
  build:
    needs: lint
    uses: Lepinoid/WorkflowCollections/.github/workflows/build.yml@main
